# Generated by Django 3.1 on 2020-09-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parttitle', models.CharField(max_length=200)),
                ('partdesc', models.CharField(max_length=500)),
            ],
        ),
    ]
