# Generated by Django 3.1 on 2020-09-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_question_partquestion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qtitle',
        ),
    ]
