# Generated by Django 3.1 on 2020-09-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0006_partquestion_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partquestion',
            name='partdesc',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
