# Generated by Django 3.1 on 2020-09-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0007_auto_20200920_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partquestion',
            name='partdesc',
            field=models.CharField(default=1, max_length=1500),
            preserve_default=False,
        ),
    ]
