# Generated by Django 3.1 on 2020-09-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0008_auto_20200920_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partquestion',
            name='partdesc',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
