# Generated by Django 3.1 on 2020-09-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0011_auto_20200920_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='qitem1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='qitem2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='qitem3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='qitem4',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
